apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: local/backend-python:latest
        imagePullPolicy: Never
        command: ["./api.sh"]
        ports:
        - containerPort: 8000